[Addon]
Name[zh_CN]=Recordian 上屏
Name=Recordian Commit
Comment[zh_CN]=把外部程序发来的文字提交到当前输入焦点
Comment=Commit text from an external program into the focused input context
Type=SharedLibrary
Library=librecordian-commit
Category=Module
Version=1.0.0
OnDemand=False

[Addon/Dependencies]
0=dbus
